environment:
  language: ruby

build:
  run: 
    meow1: echo meow1 > meow1.txt
    meow2: echo meow2 > meow2.txt
  after: echo meow3 > meow3.txt
plugins: 
  - artifacts: meow1.txt, meow2.txt, meow3.txt
