environment:
 packages:
   - gem_bundler-1.3.5_r1.9.1
build:
  before: test -f Gemfile && bundle install
  run: 
   - echo 'shell line 1'
   - echo -en 'jenkins_fold:head:section-title\r'
   - echo 'shell line 2'
   - echo 'shell line 3'
   - echo -en 'jenkins_fold:tail:section-title\r'
   - echo 'shell line 4'
